"""change register to interger

Revision ID: 6c18dfcd03b3
Revises: 
Create Date: 2026-07-30 22:35:37.046695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c18dfcd03b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('register',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('register',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
