"""change no integer into string

Revision ID: d2896db2ff1f
Revises: 6c18dfcd03b3
Create Date: 2026-07-31 09:30:24.214473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2896db2ff1f'
down_revision = '6c18dfcd03b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.String(length=100), nullable=True))
        batch_op.drop_column('feeback')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('college', sa.String(length=100), nullable=True))
        batch_op.drop_column('collage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collage', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('college')

    with op.batch_alter_table('class', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feeback', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
